on: [push]

jobs:
  blog-generation-job:
    runs-on: ubuntu-latest
    name: Automatic blog generation
    steps:
      - name: Commit Blog Generator
        uses: srajansohani/commit-blog-generator@v0.28
        with:
          blog-domain: 'srajan12.hashnode.dev'
          series-slug: 'virtual-world'
        env:
          HASHNODE_ACCESS_TOKEN: ${{ secrets.HASHNODE_ACCESS_TOKEN }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}